#logging = true

#[base16_colors]
#base00 = "#161616"
#base01 = "#262626"
#base02 = "#393939"
#base03 = "#525252"
#base04 = "#dde1e6"
#base05 = "#f2f4f8"
#base06 = "#ffffff"
#base07 = "#08bdba"
#base08 = "#3ddbd9"
#base09 = "#78a9ff"
#base0A = "#ee5396"
#base0B = "#33b1ff"
#base0C = "#ff7eb6"
#base0D = "#42be65"
#base0E = "#be95ff"
#base0F = "#82cfff"

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#696969"
blue = "#007FFF"
cyan = "#00CCCC"
green = "#03C03C"
magenta = "#FF1493"
red = "#FF2400"
white = "#FFFAFA"
yellow = "#FFD700"

[colors.normal]
black = "#10100E"
blue = "#0087BD"
cyan = "#20B2AA"
green = "#009F6B"
magenta = "#9A4EAE"
red = "#C40233"
white = "#C6C6C4"
yellow = "#FFD700"

[colors.primary]
background = "#10100E"
foreground = "#C6C6C4"

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"

[debug]
persistent_logging = true

[font]
size = 10

[font.bold]
family = "Mononoki"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Mononoki"
style = "Italic"

[font.normal]
family = "Mononoki"
style = "Normal"

[font.offset]
x = 1
y = 2

[mouse]
hide_when_typing = true

[scrolling]
history = 5000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
dynamic_padding = false
dynamic_title = true
opacity = 0.78

[window.padding]
x = 15
y = 10
